### ISSUE TITLE
Sleep chart calendar does not work with negative intervals

### ISSUE THREAD

**Issue by nydn** [alessivs/supermemo-wine#2] opened 2020-02-13 17:19 UTC
# Platform information
```
SuperMemo 17 installed with supermemo17.verb on up-to-date Arch Linux
```

## Output of `uname -rom`
```
5.5.2-zen1-1-zen x86_64 GNU/Linux
```

## Output of `wine --version`
```
wine-5.0 (Staging)
```

# Problem Description

Cannot change the calendar view to a date in the past. (negative interval in the interval dialog)
Future dates seems to be working correctly.

# Steps to reproduce
```
1. Open Sleep Chart from Tools (or F12)
2. Click on Calendar icon
3. Select a date in the past or enter negative interval
4. Click "OK"
```

# Program output (if applicable)

```
002c:fixme:win:WINNLSEnableIME hwnd 0x3021c enable -1: stub!
```

On a side note, I want to thank you for this superb guide and work you have put into this.

**Comment by nydn** [comment] 2020-02-14 17:44
It looks like, I can choose past dates, but only until the installation date. Since I installed it yesterday, I can choose yesterdays date. 
I can't remember if this is expected and it's a feature, because it was more than a year since I last installed supermemo on Windows and I don't have a Windows VM currently to test this out. So a confirmation about this would be great.

**Comment by alessivs** [comment] 2020-02-22 20:19
Since in SM17 sleep data is integrated into the learning process, the earliest date you can choose is the collection's first day (this appears to be by design). This is consistent between Windows and Wine.

If you have earlier sleep data you would like to add to the collection:

1. Download the [standalone edition of SleepChart (1.0)](http://www.supermemo.org/ftp/sleepchart.zip) and run it with `wine SleepChart.exe` (no add-ons or tweaks needed)
2. **_Edit : Set first day_** (choose the desired first day)
3. Save the sleep file in `.tim` format
4. Press F12 in SuperMemo 17, and choose **_File : Import : SleepChart file_**. Point it to the previously saved `.tim` file.

You will then be able to input or edit sleep data occurring before the collection's actual first day. 

-----

While this isn't a problem with the installer per se, and I could point you to the fact unstable releases of Wine are discouraged (I use [wine-stable](https://aur.archlinux.org/packages/wine-stable/) on Arch for my SM use), the details of your platform present a good opportunity to continue research on compatibility (see: [Compatibility tables](https://supermemopedia.com/wiki/SuperMemo_for_Windows_under_Wine#Compatibility_tables)). Winetricks managed to break, to then fix, IE compatibility for `wine>4.9` since I last updated that table. Tracked in #6.

You're welcome, and I'm glad the installer serves you well. Feel free to submit questions re: SM on Linux, or suggest a better (than gh issues) support venue.

**Comment by alessivs** [comment] 2020-02-24 20:59
Closing the issue, but feel free to add to it if needs must.

**Closed as completed by alessivs** 2020-02-24 20:59 UTC
Labels: research, wasntme

**Comment by nydn** [comment] 2020-02-25 18:07
Sorry for the late reply. Yes, I also confirmed this on a Windows VM over the weekend, it's a feature. So a nonissue.
Also thanks for the tip about the sleep chart!

About wine versions: I had some weird problems on the staging, but I'm not bound to it, so if you say current wine-stable works well, happy to revert back.

I think the current place works well regarding problem tracking/questions (i.e: I don't have any better idea.)

**Comment by alessivs** [comment] 2020-02-25 19:02
Right now Wine editions at staging and multilib are even at 5.2, which I tested to be non problematic for now, but no guarantees in the future. Wine development relies too much on active user reports to remedy its breakages, which is why I stuck with (and recommend) stable, right now only a couple point releases behind, unless you're interested in latest Wine developments for games and such.

I also have no issue with this medium. Somehow I unwatched this very repo, which is why I didn't see your issue in the beginning, but I remedied that.

**Comment by nydn** [comment] 2020-02-27 18:01
I've also switched to the wine-stable AUR package and Supermemo seems to work fine for all my use-cases in the last couple days. So this will be my main platform as well. Thanks again, for the recommendation.

**Comment by alessivs** [comment] 2020-04-20 11:34
@nydn These might interest you: https://github.com/alessivs/supermemo-miscellany#patches

**Comment by nydn** [comment] 2020-04-26 10:38
> @nydn These might interest you: https://github.com/alessivs/supermemo-miscellany#patches

Thanks for the heads up. I just got time to tinker with this. Successfully applied the 17.40 patch without any issues and it works as intended. I almost got used to the "large" icons. Thank you! :)

By the way, I'm on 5.3 wine staging, since early march and have not encountered any issues with it. So, I can recommend that if someone need staging version instead of stable.

**Comment by alessivs** [comment] 2020-04-27 12:00
You're welcome.

> By the way, I'm on 5.3 wine staging

But you're on Arch. Arch makes sense. Every distro packages things differently. If you know a better solution to [this](https://github.com/alessivs/supermemo-wine/issues/10#issuecomment-619931394) I'd appreciate your input (otherwise I'll just do as described for Debian, whose stable 4.x branch is fine for audio)
